// <auto-generated />
using System;
using Commander.WASM.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Commander.WASM.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220717165350_Init2")]
    partial class Init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Commander.WASM.Shared.Command", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommandString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParametersSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuntimeEnvironment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Commands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b25bffff-64f6-4107-92b6-ce8704707726"),
                            CommandString = "dotnet",
                            OperatingSystem = "All",
                            Parameters = "new console",
                            ParametersSummary = "Create a new console app.",
                            RuntimeEnvironment = "All"
                        },
                        new
                        {
                            Id = new Guid("346b6152-bd7f-4f3c-b461-348aad1330c5"),
                            CommandString = "dotnet",
                            OperatingSystem = "All",
                            Parameters = "new api",
                            ParametersSummary = "Create a new api.",
                            RuntimeEnvironment = "All"
                        },
                        new
                        {
                            Id = new Guid("91057720-99b8-43d4-bc73-07732bfc60ab"),
                            CommandString = "dotnet",
                            OperatingSystem = "All",
                            Parameters = "ef migrations",
                            ParametersSummary = "Create a new api.",
                            RuntimeEnvironment = "All"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
